### ISSUE TITLE
Practical example

### ISSUE THREAD

**Issue by mpariente** [bokorn/Keras-and-Theano-layers-for-Switched-Pooling#1]
Hey ! Thanks for these layers, I think they will be very helpful :) 

Would it be possible to have a practical example of how to implement a CNN with the switched max pooling please? 

For example on an architecture like this: how can I change the ```MaxPooling2D``` and ```UpSampling2D``` layers to be able to transfer the indices of ```MaxPooling2D``` to corresponding ```UpSampling2D```? 

```
model=Sequential()
model.add(ZeroPadding2D(padding=(pad,pad),dim_ordering='th',input_shape=input_shape))
model.add(Convolution2D(filter_size, kernel, kernel, border_mode='valid',dim_ordering='th'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(pool_size, pool_size),dim_ordering='th'))
model.add(Dropout(0.3))

model.add(ZeroPadding2D(padding=(pad,pad),dim_ordering='th'))
model.add(Convolution2D(2*filter_size, kernel, kernel, border_mode='valid',dim_ordering='th'))
BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(pool_size, pool_size),dim_ordering='th'))
model.add(Dropout(0.3))


model.add(ZeroPadding2D(padding=(pad,pad),dim_ordering='th'))
model.add(Convolution2D(2*filter_size, kernel, kernel, border_mode='valid',dim_ordering='th'))
model.add(BatchNormalization())
model.add(Dropout(0.3))

model.add(UpSampling2D(size=(pool_size,pool_size),dim_ordering='th'))
model.add(ZeroPadding2D(padding=(pad,pad),dim_ordering='th'))
model.add(Convolution2D(filter_size, kernel, kernel, border_mode='valid',dim_ordering='th'))
model.add(BatchNormalization())
model.add(Dropout(0.3))

model.add(UpSampling2D(size=(pool_size,pool_size),dim_ordering='th'))
model.add(ZeroPadding2D(padding=(pad,pad),dim_ordering='th'))
model.add(Convolution2D(filter_size/2, kernel, kernel, border_mode='valid',dim_ordering='th'))
model.add(BatchNormalization())

model.add(Convolution2D(1, 1, 1, border_mode='valid',activation='sigmoid',dim_ordering='th'))
```

I read the whole code of the repo but it's still not clear to me.. 
Thanks in adance!

**Comment by bokorn** [comment]
You should connect it to a UnPoolSwitch2D layer. I just pushed some example code to pool and unpool using the switched pooling.

**Comment by mpariente** [comment]
I guessed so but I'm not good with Theano yet so I couldn't really follow the code.. 
Thanks a lot for the example code, it's much clearer :) 

Are you still using this method? Did you manage to obtain similar results than some papers? For example SegNet or something?

**Comment by bokorn** [comment]
Ya, really should have had that up there before. I haven't been using it
much and don't have any comparative results. I was just testing to see if
it could be used for tracking. That work didn't really go anywhere.

-Brian

**Comment by mpariente** [comment]
What do you mean by tracking? 
I'll try to implement kind of a SegNet and let you know if it works :)

**Comment by bokorn** [comment]
I meant feature tracking, like optical flow in the feature space.
